site_name: GeoNode Cloud 
site_url: https://kan.com.ar/
nav:
  - Home: index.md
  - Project Structure: project/index.md
  - Architecture & Technology: architecture/index.md
  - Deployment: deployment/index.md

theme: 
  name: 'material'
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
  features:
    - search.suggest

plugins:
  - search
extra:
  homepage: https://kan.com.ar
  analytics:
    provider: google
    property: G-Z1CERXCTNQ
  alternate:
    - name: English
      lang: en
    - name: Spanish
      lang: es
repo_url: https://github.com/Kan-T-IT/geonode_cloud_documentation


  
